# Generated by Django 3.1 on 2021-01-09 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(new_price__gt=Decimal('0')), name='new_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(old_price__gt=Decimal('0')), name='old_price_gt_0'),
        ),
    ]
